from sqlalchemy import Column, Float, String, Integer, Text, Boolean

from core.db import Base
from core.db.mixins import TimestampMixin


class Product(Base, TimestampMixin):
    __tablename__ = "products"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(200), nullable=False, unique=False)
    added_by = Column(String(6), nullable=False)
    user_id = Column(Integer, nullable=False)
    category_id = Column(Integer, nullable=False)
    brand_id = Column(Integer, nullable=True)
    photos = Column(Text, nullable=True)
    thumbnail_img = Column(String(100), nullable=True)
    video_provider = Column(String(20), nullable=True)
    video_link = Column(String(100), nullable=True)
    tags = Column(Text, nullable=True)
    description = Column(Text, nullable=True)
    unit_price = Column(Float(precision=2), nullable=False)
    purchase_price = Column(Float(precision=2), nullable=True)
    variant_product = Column(Integer, nullable=False, default=0)
    attributes = Column(Text, nullable=False)
    choice_options = Column(Text, nullable=True)
    colors = Column(Text, nullable=True)
    variations = Column(Text, nullable=True)
    todays_deal = Column(Integer, nullable=False, default=1)
    published = Column(Integer, nullable=False, default=1)
    approved = Column(Boolean, nullable=False, default=1)
    stock_visibility_state = Column(String(10), nullable=False, default='quantity')
    cash_on_delivery = Column(Boolean, nullable=False, default=1)
    featured = Column(Integer, nullable=False, default=0)
    seller_featured = Column(Integer, nullable=False, default=0)
    current_stock = Column(Integer, nullable=False, default=0)
    unit = Column(String(20), nullable=True)
    min_qty = Column(Integer, nullable=False, default=1)
    low_stock_quantity = Column(Integer, nullable=True)
    discount = Column(Float(precision=2), nullable=True)
    discount_type = Column(String(10), nullable=True)
    discount_start_date = Column(Integer, nullable=True)
    discount_end_date = Column(Integer, nullable=True)
    tax = Column(Float(precision=2), nullable=True)
    tax_type = Column(String(10), nullable=True)
    shipping_type = Column(String(10), nullable=True, default='flat_rate')
    shipping_cost = Column(Text, nullable=True)
    is_quantity_multiplied = Column(Boolean, nullable=False, default=0)
    est_shipping_days = Column(Integer, nullable=True)
    num_of_sale = Column(Integer, nullable=False, default=0)
    meta_title = Column(Text, nullable=True)
    meta_description = Column(Text, nullable=True)
    meta_img = Column(String, nullable=True)
    pdf = Column(String, nullable=True)
    slug = Column(Text, nullable=False)
    rating = Column(Float(precision=2), nullable=False, default=0)
    barcode = Column(String, nullable=True)
    digital = Column(Integer, nullable=False, default=0)
    auction_product = Column(Integer, nullable=False, default=0)
    file_name = Column(String, nullable=True)
    file_path = Column(String, nullable=True)